// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmshe91a7Zlz4-zNkPwC7Ov8RuBRsfh6o',
    appId: '1:487236760247:web:5b909e8669fa29e4bc5332',
    messagingSenderId: '487236760247',
    projectId: 'loginpage-ccfc7',
    authDomain: 'loginpage-ccfc7.firebaseapp.com',
    storageBucket: 'loginpage-ccfc7.firebasestorage.app',
    measurementId: 'G-CSNJHJSWFW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxLcblsFXaVWoXmXDVDGvB7TOWxZReF2A',
    appId: '1:487236760247:android:40a35d87882a54ebbc5332',
    messagingSenderId: '487236760247',
    projectId: 'loginpage-ccfc7',
    storageBucket: 'loginpage-ccfc7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT5401uOEqvFGuSWO94UCMSQkWnlaldyc',
    appId: '1:487236760247:ios:5c2b009f654ffab1bc5332',
    messagingSenderId: '487236760247',
    projectId: 'loginpage-ccfc7',
    storageBucket: 'loginpage-ccfc7.firebasestorage.app',
    iosClientId: '487236760247-2it40anuf6ptdatu22smb92c1k1bufar.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginpage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT5401uOEqvFGuSWO94UCMSQkWnlaldyc',
    appId: '1:487236760247:ios:5c2b009f654ffab1bc5332',
    messagingSenderId: '487236760247',
    projectId: 'loginpage-ccfc7',
    storageBucket: 'loginpage-ccfc7.firebasestorage.app',
    iosClientId: '487236760247-2it40anuf6ptdatu22smb92c1k1bufar.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginpage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmshe91a7Zlz4-zNkPwC7Ov8RuBRsfh6o',
    appId: '1:487236760247:web:529b16b0e51d62d5bc5332',
    messagingSenderId: '487236760247',
    projectId: 'loginpage-ccfc7',
    authDomain: 'loginpage-ccfc7.firebaseapp.com',
    storageBucket: 'loginpage-ccfc7.firebasestorage.app',
    measurementId: 'G-VC68K0QRDG',
  );
}
